# Generated by Django 3.2.14 on 2022-12-15 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(default=1, max_length=25, verbose_name='Caracteristica')),
                ('info_caracteristica', models.TextField(verbose_name='info de caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(default=1, max_length=25, verbose_name='Funcion')),
                ('info_Funcion', models.TextField(verbose_name='info de funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(default=1, max_length=25, verbose_name='Tamaño')),
                ('info_tamaño', models.TextField(verbose_name='info del tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('Ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('preparacion', models.TextField(verbose_name='Preparacion')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_de_tragos.caracteristica', verbose_name='Caracteristica')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_de_tragos.funcion', verbose_name='Función')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_de_tragos.tamaño', verbose_name='tamaño')),
            ],
        ),
    ]
